### ISSUE TITLE
jkhub.net is gone

### ISSUE THREAD

**Issue by LukasThyWalls** [The-MAZZTer/jkversions#1]
So this tool do nothing now. I don't know if it can do the patch in local if i found the files somewhere else (i only found the 1.0.1 patch).

All DF2:JK modding i found almost everywhere relies in jkhub.net... so what a bummer...

Thanks.

**Comment by LukasThyWalls** [comment]
I just find that Google Cache has stored a copy of the web from 9 March... Maybe jkhub.net is affected by the OVH fire?

Edit: It seems that is what happened [https://builtwith.com/jkhub.net](https://builtwith.com/jkhub.net)

**Comment by The-MAZZTer** [comment]
I will probably make changes to have JK Versions look for locally downloaded patch files, make the download urls customizable, and allow skipping optional files.

**Comment by The-MAZZTer** [comment]
Latest release allows you to specify custom URLs or use local files, working around this problem.

http://jkjunkie.com/JKBot/JKArchive/JKDF2/JKDF2/Game%20Files/tools/PATCH/old/ has working files (I used them to test) so you can use the ones from there.

I didn't use them as default URLs since it wasn't clear to me who runs that site or if they would mind if I set that as a default.

**Comment by LukasThyWalls** [comment]
Thanks to look it up!

This is the source of almost every page to find the original EXEs,to mod JK, so at least there is a workaround.

However, i hope JKHUB.NET is not gone forever...
